// frontend/packages/root/src/components/data/data-table.tsx
import { useDataContext } from "@/plugins/store";
import { FC, useState, useMemo, useEffect } from "react";

interface Column {
  key: string;
  label: string;
  sort: boolean;
  width?: string;
  class?: string;
  check?: boolean;
}

interface TableProps {
  data: Record<string, unknown>[];
  columns: Column[];
}

const DataTable: FC<TableProps> = ({ data, columns }) => {
  const [sortColumn, setSortColumn] = useState<string>("");
  const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc");
  const [selectedRecords, setSelectedRecords] = useState<
    Record<string, unknown>[]
  >([]);
  const [selectAll, setSelectAll] = useState<boolean>(false);

  const { currentPage, itemsPerPage, searchQuery, updateTotalRecords } =
    useDataContext();

  const filteredRecords = useMemo(() => {
    if (!data || data.length === 0) {
      return [];
    }

    const query = searchQuery.toLowerCase();

    const filtered = data.filter((record) =>
      Object.values(record).some((value) => {
        if (typeof value === "string" || typeof value === "number") {
          return value.toString().toLowerCase().includes(query);
        }
        return false;
      })
    );

    const sorted = filtered.sort((a, b) => {
      const compareA =
        typeof a[sortColumn] === "string"
          ? a[sortColumn]?.toString().toLowerCase()
          : "";
      const compareB =
        typeof b[sortColumn] === "string"
          ? b[sortColumn]?.toString().toLowerCase()
          : "";
      if (compareA < compareB) return sortOrder === "asc" ? -1 : 1;
      if (compareA > compareB) return sortOrder === "asc" ? 1 : -1;
      return 0;
    });

    return sorted;
  }, [data, searchQuery, sortColumn, sortOrder]);

  useEffect(() => {
    updateTotalRecords(filteredRecords.length);
  }, [filteredRecords, updateTotalRecords]);

  const paginatedRecords = useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    const end = start + itemsPerPage;
    return filteredRecords.slice(start, end);
  }, [filteredRecords, currentPage, itemsPerPage]);

  const changeSort = (column: string, sort: boolean = true) => {
    if (!sort) return;
    if (sortColumn === column) {
      setSortOrder(sortOrder === "asc" ? "desc" : "asc");
    } else {
      setSortColumn(column);
      setSortOrder("asc");
    }
  };

  const toggleSelectAll = () => {
    setSelectAll(!selectAll);
    if (!selectAll) {
      setSelectedRecords([...paginatedRecords]);
    } else {
      setSelectedRecords([]);
    }
  };

  const handleSelectRecord = (record: Record<string, unknown>) => {
    setSelectedRecords((prevSelected) => {
      if (prevSelected.includes(record)) {
        return prevSelected.filter((r) => r !== record);
      } else {
        return [...prevSelected, record];
      }
    });
  };

  return (
    <div className="h-screen w-screen">
      <div className="overflow-x-auto shadow-md bg-white rounded-sm">
        <table className="min-w-full bg-white border border-gray-200">
          <thead>
            <tr className="bg-gray-200 border-b border-gray-300">
              {columns.map((column) => (
                <th
                  key={column.key}
                  className="p-2 text-left text-gray-600 cursor-pointer hover:bg-gray-300 transition-colors text-md font-medium"
                  onClick={() => changeSort(column.key, column.sort)}
                >
                  {column.check ? (
                    <input
                      type="checkbox"
                      className="cursor-pointer"
                      checked={selectAll}
                      onChange={toggleSelectAll}
                    />
                  ) : (
                    <>
                      {column.label}
                      {sortColumn === column.key && column.sort && (
                        <span className="ml-1 text-md">
                          {sortOrder === "asc" ? "↑" : "↓"}
                        </span>
                      )}
                    </>
                  )}
                </th>
              ))}
            </tr>
          </thead>

          <tbody>
            {paginatedRecords.map(
              (
                record,
                index
              ) => (
                <tr
                  key={(record[columns[0].key] as string) || index}
                  className="border-b border-dashed border-gray-300 transition-all hover:shadow-md text-md"
                >
                  {columns.map((column) => (
                    <td
                      key={column.key}
                      className={`p-1 ${column.class || ""}`}
                    >
                      {column.check ? (
                        <input
                          type="checkbox"
                          className="cursor-pointer"
                          checked={selectedRecords.includes(record)}
                          onChange={() => handleSelectRecord(record)}
                        />
                      ) : (
                        <span
                          dangerouslySetInnerHTML={{
                            __html: record[column.key] as string,
                          }}
                        />
                      )}
                    </td>
                  ))}
                </tr>
              )
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default DataTable;

// frontend/libraries/library/src/components/data/DataTable.vue
<script setup lang="ts">
import { useTableStore } from '@/store';
import { ref, computed } from 'vue';

const props = defineProps({
    data: {
        type: Array as () => Record<string, any>[],
        default: () => [],
    },
    columns: {
        type: Array as () => {
            key: string,
            label: string,
            sort?: boolean,
            width?: string,
            class?: string,
            check?: boolean
        }[],
        default: () => []
    },
    checkColumn: {
        type: Boolean,
        default: false,
    }
});

const tableStore = useTableStore();

const itemsPerPage = computed(() => tableStore.itemsPerPage);
const sortColumn = ref<string>('');
const sortOrder = ref<'asc' | 'desc'>('asc');
const selectedRecords = ref<Record<string, any>[]>([]);
const selectAll = ref(false);

const filteredRecords = computed(() => {
    const query = tableStore.searchQuery.toLowerCase();
    const filteredRecords = props.data.filter(record =>
        Object.values(record).some(value =>
            value.toString().toLowerCase().includes(query)
        )
    ).sort((a, b) => {
        const compareA = a[sortColumn.value]?.toString().toLowerCase() || '';
        const compareB = b[sortColumn.value]?.toString().toLowerCase() || '';
        if (compareA < compareB) return sortOrder.value === 'asc' ? -1 : 1;
        if (compareA > compareB) return sortOrder.value === 'asc' ? 1 : -1;
        return 0;
    });

    tableStore.updateTotalRecords(filteredRecords.length);
    return filteredRecords;
});

const paginatedRecords = computed(() => {
    const start = (tableStore.currentPage - 1) * itemsPerPage.value;
    const end = start + itemsPerPage.value;
    return filteredRecords.value.slice(start, end);
});

const changeSort = (column: string, sort: boolean = true) => {
    if (!sort) {
        return;
    }
    if (sortColumn.value === column) {
        sortOrder.value = sortOrder.value === 'asc' ? 'desc' : 'asc';
    } else {
        sortColumn.value = column;
        sortOrder.value = 'asc';
    }
};

const toggleSelectAll = () => {
    if (selectAll.value) {
        selectedRecords.value = [...paginatedRecords.value];
    } else {
        selectedRecords.value = [];
    }
};

</script>

<template>
    <div>
        <div class="overflow-x-auto rounded-sm shadow-md">
            <table class="table-auto w-full border-collapse">
                <thead>
                    <tr class="border-b bg-gray-50 border-gray-300">
                        <template v-for="column in props.columns" :key="column.key">
                            <th v-if="column.check ?? false" class="cursor-pointer">
                                <input class="cursor-pointer" type="checkbox" v-model="selectAll"
                                    @change="toggleSelectAll" />
                            </th>
                            <th v-else @click="changeSort(column.key, column.sort ?? false)"
                                :class="['cursor-pointer', column.class || '']"
                                :style="{ width: column.width || 'auto' }">
                                {{ column.label }}
                                <span v-if="sortColumn === column.key && column.sort !== false" class="ml-1 text-md">
                                    {{ sortOrder === 'asc' ? '↑' : '↓' }}
                                </span>
                            </th>
                        </template>
                    </tr>
                </thead>

                <tbody class="text-sm">
                    <tr v-for="(record, index) in paginatedRecords" :key="record[props.columns[0].key]" :class="[
                        index % 2 === 0 ? 'bg-gray-50' : 'bg-white',
                        'hover:shadow-lg hover:bg-gray-100 transition-shadow duration-200'
                    ]">
                        <template v-for="column in props.columns">
                            <template v-if="column.check ?? false">
                                <td class="cursor-pointer text-center">
                                    <input class="cursor-pointer" type="checkbox" v-model="selectedRecords"
                                        :value="record" />
                                </td>
                            </template>
                            <template v-else>
                                <td class="p-2" :class="column.class || ''" :style="{ width: column.width || 'auto' }"
                                    :key="column.key">
                                    <slot :name="column.key" :field="column.key" :row="record"
                                        v-if="$slots[column.key]"></slot>
                                    <span v-html="record[column.key]" v-else></span>
                                </td>
                            </template>
                        </template>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="mt-4 text-sm flex justify-between items-center">
            <div>
                Showing {{ (tableStore.currentPage - 1) * itemsPerPage + 1 }} to
                {{ Math.min(tableStore.currentPage * itemsPerPage, filteredRecords.length) }} of
                {{ filteredRecords.length }} records
            </div>
        </div>

    </div>
</template>

<style scoped>
.overflow-x-auto {
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
}

thead tr th {
    height: 40px;
}
</style>
