// frontend/c3k-utilities/src/components/data/data-table.tsx
import { FC, useState, useMemo, useEffect, ReactNode } from "react";
import { useDataContext } from "../../plugins/store";

interface Column {
  key: string;
  label: string;
  sort: boolean;
  width?: string;
  class?: string;
  check?: boolean;
  render?: (record: Record<string, unknown>) => ReactNode;
}

interface TableProps {
  data: Record<string, unknown>[];
  columns: Column[];
  onSelectionChange?: (selected: Record<string, unknown>[]) => void;
}

const DataTable: FC<TableProps> = ({ data, columns, onSelectionChange }) => {
  const [sortColumn, setSortColumn] = useState<string>("");
  const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc");
  const [selectedRecords, setSelectedRecords] = useState<
    Record<string, unknown>[]
  >([]);
  const [selectAll, setSelectAll] = useState<boolean>(false);

  const { currentPage, itemsPerPage, searchQuery, updateTotalRecords } =
    useDataContext();

  const filteredRecords = useMemo(() => {
    if (!data || data.length === 0) {
      return [];
    }

    const query = searchQuery.toLowerCase();

    const filtered = data.filter((record) =>
      Object.values(record).some((value) => {
        if (typeof value === "string" || typeof value === "number") {
          return value.toString().toLowerCase().includes(query);
        }
        return false;
      })
    );

    const sorted = filtered.sort((a, b) => {
      const compareA =
        typeof a[sortColumn] === "string"
          ? a[sortColumn]?.toString().toLowerCase()
          : "";
      const compareB =
        typeof b[sortColumn] === "string"
          ? b[sortColumn]?.toString().toLowerCase()
          : "";
      if (compareA < compareB) return sortOrder === "asc" ? -1 : 1;
      if (compareA > compareB) return sortOrder === "asc" ? 1 : -1;
      return 0;
    });

    return sorted;
  }, [data, searchQuery, sortColumn, sortOrder]);

  useEffect(() => {
    updateTotalRecords(filteredRecords.length);
  }, [filteredRecords, updateTotalRecords]);

  const paginatedRecords = useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    const end = start + itemsPerPage;
    return filteredRecords.slice(start, end);
  }, [filteredRecords, currentPage, itemsPerPage]);

  const changeSort = (column: string, sort: boolean = true) => {
    if (!sort) return;
    if (sortColumn === column) {
      setSortOrder(sortOrder === "asc" ? "desc" : "asc");
    } else {
      setSortColumn(column);
      setSortOrder("asc");
    }
  };

  const toggleSelectAll = () => {
    setSelectAll(!selectAll);
    const newSelectedRecords = !selectAll ? [...paginatedRecords] : [];
    setSelectedRecords(newSelectedRecords);

    if (onSelectionChange) {
      onSelectionChange(newSelectedRecords);
    }
  };

  const handleSelectRecord = (record: Record<string, unknown>) => {
    setSelectedRecords((prevSelected) => {
      if (prevSelected.includes(record)) {
        return prevSelected.filter((r) => r !== record);
      } else {
        return [...prevSelected, record];
      }
    });
  };

  const renderColumnContent = (
    record: Record<string, unknown>,
    column: Column
  ): ReactNode => {
    if (column.render) {
      return column.render(record);
    }
    return (record[column.key] as ReactNode) || null;
  };

  return (
    <table>
      <thead>
        <tr className="bg-gray-200 border-b border-gray-300">
          {columns.map((column) => (
            <th
              key={column.key}
              onClick={() => changeSort(column.key, column.sort)}
            >
              {column.check ? (
                <input
                  type="checkbox"
                  className="cursor-pointer"
                  checked={selectAll}
                  onChange={toggleSelectAll}
                />
              ) : (
                <>
                  {column.label}
                  {sortColumn === column.key && column.sort && (
                    <span className="ml-1 text-md">
                      {sortOrder === "asc" ? "↑" : "↓"}
                    </span>
                  )}
                </>
              )}
            </th>
          ))}
        </tr>
      </thead>

      <tbody>
        {paginatedRecords.map((record, index) => (
          <tr
            key={(record[columns[0].key] as string) || index}
          >
            {columns.map((column) => (
              <td key={column.key} className={`p-1 ${column.class || ""}`}>
                {column.check ? (
                  <div className="flex items-center justify-center h-full">
                    <input
                      type="checkbox"
                      className="cursor-pointer"
                      checked={selectedRecords.includes(record)}
                      onChange={() => handleSelectRecord(record)}
                    />
                  </div>
                ) : (
                  renderColumnContent(record, column)
                )}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
};

export default DataTable;

// frontend/packages/c3k-library/src/components/data/DataTable.vue
<script setup lang="ts">
import { useTableStore } from '@/plugins/store';
import { ref, computed } from 'vue';

const props = defineProps({
    data: {
        type: Array as () => Record<string, any>[],
        default: () => [],
    },
    columns: {
        type: Array as () => {
            key: string,
            label: string,
            sort: boolean,
            width: string,
            class: string,
            check: boolean
        }[],
        default: () => []
    },
    checkColumn: {
        type: Boolean,
        default: false,
    }
});

const tableStore = useTableStore();

const itemsPerPage = computed(() => tableStore.itemsPerPage);
const sortColumn = ref<string>('');
const sortOrder = ref<'asc' | 'desc'>('asc');
const selectedRecords = ref<Record<string, any>[]>([]);
const selectAll = ref(false);

const filteredRecords = computed(() => {
    const query = tableStore.searchQuery.toLowerCase();
    const filteredRecords = props.data.filter(record =>
        Object.values(record).some(value =>
            value.toString().toLowerCase().includes(query)
        )
    ).sort((a, b) => {
        const compareA = a[sortColumn.value]?.toString().toLowerCase() || '';
        const compareB = b[sortColumn.value]?.toString().toLowerCase() || '';
        if (compareA < compareB) return sortOrder.value === 'asc' ? -1 : 1;
        if (compareA > compareB) return sortOrder.value === 'asc' ? 1 : -1;
        return 0;
    });

    tableStore.updateTotalRecords(filteredRecords.length);
    return filteredRecords;
});

const paginatedRecords = computed(() => {
    const start = (tableStore.currentPage - 1) * itemsPerPage.value;
    const end = start + itemsPerPage.value;
    return filteredRecords.value.slice(start, end);
});

const changeSort = (column: string, sort: boolean = true) => {
    if (!sort) {
        return;
    }
    if (sortColumn.value === column) {
        sortOrder.value = sortOrder.value === 'asc' ? 'desc' : 'asc';
    } else {
        sortColumn.value = column;
        sortOrder.value = 'asc';
    }
};

const toggleSelectAll = () => {
    if (selectAll.value) {
        selectedRecords.value = [...paginatedRecords.value];
    } else {
        selectedRecords.value = [];
    }
};
</script>

<template>
    <table>
        <thead>
            <tr class="bg-gray-100 border-b border-gray-300">
                <template v-for="column in props.columns" :key="column.key">
                    <th v-if="column.check"
                        class="cursor-pointer">
                        <input class="cursor-pointer" type="checkbox" v-model="selectAll" @change="toggleSelectAll" />
                    </th>
                    <th v-else @click="changeSort(column.key, column.sort)"
                        class="cursor-pointer ">
                        {{ column.label }}
                        <span v-if="sortColumn === column.key && column.sort" class="ml-1 text-md">
                            {{ sortOrder === 'asc' ? '↑' : '↓' }}
                        </span>
                    </th>
                </template>
            </tr>
        </thead>
        <tbody>
            <tr v-for="record in paginatedRecords" :key="record[props.columns[0].key]">
                <template v-for="column in props.columns">
                    <template v-if="column.check">
                        <td class="cursor-pointer text-center">
                            <input class="cursor-pointer" type="checkbox" v-model="selectedRecords" :value="record" />
                        </td>
                    </template>
                    <template v-else>
                        <td class="p-1" :class="column.class" :key="column.key"
                            v-if="typeof $slots[column.key] !== 'undefined'">
                            <slot :name="column.key" :field="column.key" :row="record"></slot>
                        </td>
                        <td class="p-1" :class="column.class" :key="column.key + `-els`" v-else>
                            <span v-html="record[column.key]"></span>
                        </td>
                    </template>
                </template>
            </tr>
        </tbody>
    </table>
</template>

<style scoped></style>
