// frontend/packages/application-root/src/layouts/components/authentication/Footer.vue
<script setup lang="ts">
import { config } from 'c3k-library';

</script>
<template>
    <footer class="fixed text-xs w-auto justify-end bottom-0 right-0 bg-gray-50 py-2 px-4 flex items-center">
        <p class="text-gray-500">
            Copyright © 2024 {{ config.application }} by
            <a href="https://combinesoft.net" class="text-gray-500 hover:text-gray-800" target="_blank">
                COMBINE CHIPSoft
            </a>
        </p>
    </footer>
</template>

// frontend/packages/root/src/components/layout/auth/footer.tsx
import { FC } from "react";
import { config } from "@/plugins/config";

const Footer: FC = () => {
  return (
    <>
      <footer className="fixed text-xs w-auto justify-end bottom-0 right-0 bg-gray-100 py-2 px-4 flex items-center">
        <p className="text-gray-500">
          Copyright © 2024 {config.application} by
          <a
            href="https://combinesoft.net"
            className="text-gray-500 hover:text-gray-800"
            target="_blank"
          >
            {config.company}
          </a>
        </p>
      </footer>
    </>
  );
};

export default Footer;
